In [1]:
import pandas as pd
import numpy as np

In [2]:
game_summary=pd.read_csv('game_summary.csv')
print(game_summary)

             game_date_est  game_sequence   game_id  game_status_id  \
0      1946-11-01 00:00:00            NaN  24600001               3
1      1946-11-02 00:00:00            NaN  24600003               3
2      1946-11-02 00:00:00            NaN  24600002               3
3      1946-11-02 00:00:00            NaN  24600004               3
4      1946-11-02 00:00:00            NaN  24600005               3
...                    ...            ...       ...             ...
58105  2023-06-07 00:00:00            1.0  42200403               3
58106  2023-06-09 00:00:00            1.0  42200404               3
58107  2023-06-12 00:00:00            1.0  42200405               3
58108  2023-02-19 00:00:00            1.0  32200001               3
58109  2023-02-19 00:00:00            1.0  32200001               3

      game_status_text         gamecode  home_team_id  visitor_team_id  \
0                  NaN  19461101/NYKHUS    1610610035       1610612752
1                  NaN  19461102/PITBOM    1610610034       1610610031
2                  NaN  19461102/BOSPRO    1610610032       1610612738
3                  NaN  19461102/NYKCHS    1610610025       1610612752
4                  NaN  19461102/WASDEF    1610610028       1610610036
...                ...              ...           ...              ...
58105            Final  20230607/DENMIA    1610612748       1610612743
58106            Final  20230609/DENMIA    1610612748       1610612743
58107            Final  20230612/MIADEN    1610612743       1610612748
58108            Final  20230219/GNSLBN    1610616834       1610616833
58109            Final  20230219/GNSLBN    1610616834       1610616833

       season  live_period live_pc_time natl_tv_broadcaster_abbreviation  \
0        1946            5          NaN                              NaN
1        1946            4          NaN                              NaN
2        1946            4          NaN                              NaN
3        1946            4          NaN                              NaN
4        1946            4          NaN                              NaN
...       ...          ...          ...                              ...
58105    2022            4                                           ABC
58106    2022            4                                           ABC
58107    2022            4                                           ABC
58108    2022            4                                       TNT/TBS
58109    2022            4                                       TNT/TBS

      live_period_time_bcast  wh_status
0                     Q5  -           1
1                     Q4  -           1
2                     Q4  -           1
3                     Q4  -           1
4                     Q4  -           1
...                      ...        ...
58105         Q4       - ABC          1
58106         Q4       - ABC          1
58107         Q4       - ABC          1
58108     Q4       - TNT/TBS          1
58109     Q4       - TNT/TBS          1

[58110 rows x 14 columns]

In [3]:
# Convertir la columna 'fecha' a formato datetime 
game_summary['game_date_est'] = pd.to_datetime(game_summary['game_date_est'])

#2018 en adelante
game_summary_filtrada= game_summary[game_summary['game_date_est'] >  '2018-10-01']

# Verificar el resultado
game_summary_filtrada

,game_date_est,game_sequence,game_id,game_status_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,live_pc_time,natl_tv_broadcaster_abbreviation,live_period_time_bcast,wh_status
52212,2018-10-16,1.0,21800001,3,Final,20181016/PHIBOS,1610612738,1610612755,2018,4,NaN,TNT,Q4 - TNT,1
52213,2018-10-16,2.0,21800002,3,Final,20181016/OKCGSW,1610612744,1610612760,2018,4,NaN,TNT,Q4 - TNT,1
52214,2018-10-17,8.0,21800010,3,Final,20181017/MINSAS,1610612759,1610612750,2018,4,NaN,NaN,Q4 -,1
52215,2018-10-17,11.0,21800013,3,Final,20181017/DALPHX,1610612756,1610612742,2018,4,NaN,ESPN,Q4 - ESPN,1
52216,2018-10-17,10.0,21800012,3,Final,20181017/DENLAC,1610612746,1610612743,2018,4,NaN,NaN,Q4 -,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58105,2023-06-07,1.0,42200403,3,Final,20230607/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58106,2023-06-09,1.0,42200404,3,Final,20230609/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58107,2023-06-12,1.0,42200405,3,Final,20230612/MIADEN,1610612743,1610612748,2022,4,,ABC,Q4 - ABC,1
58108,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1
58109,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1

In [4]:
print(game_summary_filtrada.isnull().sum())

game_date_est                          0
game_sequence                          0
game_id                                0
game_status_id                         0
game_status_text                       0
gamecode                               0
home_team_id                           0
visitor_team_id                        0
season                                 0
live_period                            0
live_pc_time                        3877
natl_tv_broadcaster_abbreviation    4151
live_period_time_bcast                 0
wh_status                              0
dtype: int64

In [5]:
game_summary_live_pc_time=pd.unique(game_summary_filtrada["live_pc_time"])
game_summary_live_pc_time

array([nan, '     '], dtype=object)

In [6]:
game_summary_filtrada = game_summary_filtrada.drop('live_pc_time', axis=1)
game_summary_filtrada

,game_date_est,game_sequence,game_id,game_status_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,natl_tv_broadcaster_abbreviation,live_period_time_bcast,wh_status
52212,2018-10-16,1.0,21800001,3,Final,20181016/PHIBOS,1610612738,1610612755,2018,4,TNT,Q4 - TNT,1
52213,2018-10-16,2.0,21800002,3,Final,20181016/OKCGSW,1610612744,1610612760,2018,4,TNT,Q4 - TNT,1
52214,2018-10-17,8.0,21800010,3,Final,20181017/MINSAS,1610612759,1610612750,2018,4,NaN,Q4 -,1
52215,2018-10-17,11.0,21800013,3,Final,20181017/DALPHX,1610612756,1610612742,2018,4,ESPN,Q4 - ESPN,1
52216,2018-10-17,10.0,21800012,3,Final,20181017/DENLAC,1610612746,1610612743,2018,4,NaN,Q4 -,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58105,2023-06-07,1.0,42200403,3,Final,20230607/DENMIA,1610612748,1610612743,2022,4,ABC,Q4 - ABC,1
58106,2023-06-09,1.0,42200404,3,Final,20230609/DENMIA,1610612748,1610612743,2022,4,ABC,Q4 - ABC,1
58107,2023-06-12,1.0,42200405,3,Final,20230612/MIADEN,1610612743,1610612748,2022,4,ABC,Q4 - ABC,1
58108,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,TNT/TBS,Q4 - TNT/TBS,1
58109,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,TNT/TBS,Q4 - TNT/TBS,1

In [7]:
game_summary_live_pc_time=pd.unique(game_summary_filtrada["game_status_id"])
game_summary_live_pc_time

array([3])

In [8]:
#Elimini columnas que tienen valores unicos que no sirven para el analisis y natl_tv, que muestra una abrieviatura del canal que trasmitio el partido, informacion que tambien tengo en live period y tiene mas de 4000 nulos.
game_summary_filtrada = game_summary_filtrada.drop(['natl_tv_broadcaster_abbreviation', 'game_status_id', 'wh_status' ], axis=1)
game_summary_filtrada

,game_date_est,game_sequence,game_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,live_period_time_bcast
52212,2018-10-16,1.0,21800001,Final,20181016/PHIBOS,1610612738,1610612755,2018,4,Q4 - TNT
52213,2018-10-16,2.0,21800002,Final,20181016/OKCGSW,1610612744,1610612760,2018,4,Q4 - TNT
52214,2018-10-17,8.0,21800010,Final,20181017/MINSAS,1610612759,1610612750,2018,4,Q4 -
52215,2018-10-17,11.0,21800013,Final,20181017/DALPHX,1610612756,1610612742,2018,4,Q4 - ESPN
52216,2018-10-17,10.0,21800012,Final,20181017/DENLAC,1610612746,1610612743,2018,4,Q4 -
...,...,...,...,...,...,...,...,...,...,...
58105,2023-06-07,1.0,42200403,Final,20230607/DENMIA,1610612748,1610612743,2022,4,Q4 - ABC
58106,2023-06-09,1.0,42200404,Final,20230609/DENMIA,1610612748,1610612743,2022,4,Q4 - ABC
58107,2023-06-12,1.0,42200405,Final,20230612/MIADEN,1610612743,1610612748,2022,4,Q4 - ABC
58108,2023-02-19,1.0,32200001,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,Q4 - TNT/TBS
58109,2023-02-19,1.0,32200001,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,Q4 - TNT/TBS

In [9]:
game_summary_filtrada.to_csv("game_summary_filtrada.csv", index=False)

In [7]:
import pandas as pd
from sqlalchemy import create_engine

# Leer el CSV
df = pd.read_csv('game_summary_filtrada.csv')

# Parámetros de conexión a SQL Server
server = 'server-sql-grupo1.database.windows.net'
database = 'NBA'
username = 'Admon'
password = 'Password.Server1'

# Crear la URL de conexión
connection_string = f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'

# Crear el motor de conexión
engine = create_engine(connection_string)

# Subir el DataFrame a SQL Server (especificando el nombre de la tabla)
df.to_sql('game_summary_filtrada', con=engine, if_exists='replace', index=False)

46